### ISSUE TITLE
add home function to reset the view to the home transformation for the current window

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/gepetto-viewer-corba#34]

**Comment by jmirabel** [comment]
There exists a function related to what you want: `attachCameraToNode`. Did you have a look ?

**Comment by nmansard** [comment]
I agree this functionality would be interesting. 
attachCameraToNode attaches (fix) the camera to a node, so it is node the requested feature. 
BTW, it would also be interesting to have in the API a function to get the current placement of the camera.

what about:
wm->getCameraTransformation(windowsid)  // return translation + quaternion
wm->setCameraTransformation(windowsid,transformation)

**Comment by jmirabel** [comment]
See d7aa759 and c14af07 for `getCameraTransformation` and `setCameraTransformation`

**Comment by nmansard** [comment]
Thx. I am testing it and will close the issue.

**Comment by nmansard** [comment]
That is exactly what I wanted. 
I think it is answering quite well to the initial request of @jcarpent (just store the initial camera placement in your client, and set the camera back to the configuration when you want it). Also considering the age of this issue, I close it and let @jcarpent or other re-open it if the mentioned solution is not sufficient.
