### ISSUE TITLE
Quaternion convention

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/gepetto-viewer-corba#38]
Internally, the viewer is using the OSG convention (X,Y,Z,W) to represent quaternions. However, the python API convention is inverted to (W,X,Y,Z).

As most (if not all) software in the team switch to Pinocchio, most of them will also use the (X,Y,Z,W) convention, used by Eigen. I think it is simpler to use the same convention everywhere and propose to switch to (X,Y,Z,W) in the python bindings as well.

Anyone against such a change ?

**Comment by jcarpent** [comment]
:+1:

**Comment by nmansard** [comment]
I agree too. Should we also add an option to enforce back compatibility? 
@jmirabel : would you be available to implement the patch in GV and GVC? I can propagate it in Pinocchio.

**Comment by jmirabel** [comment]
This has been addressed.
