### ISSUE TITLE
terminate called after throwing an instance of 'CORBA::NO_RESOURCES'

### ISSUE THREAD

**Issue by andreadelprete** [humanoid-path-planner/gepetto-viewer-corba#42]
Using robotpkg I installed gepetto-viewer and gepetto-viewer-corba on a "fresh" virtual machine running ubuntu 14.04. Now when I run gepetto-viewer-server I get this error:

> terminate called after throwing an instance of 'CORBA::NO_RESOURCES'

Any idea what the problem might be? At first I thought I didn't have given to the virtual box enough memory, but now it has 4 GB and the error is still there.

**Comment by jcarpent** [comment]
It seems that Corba has not been initialised with `omniNames -start`

**Comment by jmirabel** [comment]
Have a look at the last section of the readme.

**Comment by andreadelprete** [comment]
@jcarpent I don't get what you are suggesting me to do.
@jmirabel The error described in the last section of the readme is about CORBA::TRANSIENT, which is a problem I previously had, but now I think I solved it by following those instructions. After solving it the error became CORBA::NO_RESOURCES

**Comment by jmirabel** [comment]
I would look into network configuration issues.

Does any of the following commands give an error ?
```
nameclt list
ifconfig lo
```
`nmap localhost -p 2809` says that the port is open ?

**Comment by jmirabel** [comment]
Can you give a try fo start `gepetto-gui` instead of `gepetto-viewer-server` ?
I don't think it will solve the issue but it's worth trying.

**Comment by jcarpent** [comment]
You just need to run for the first time omniNames with the command `omniNames -start`.  It will create a config file in /etc/.
Afterwards, you won't need to redo the operation and omniNames will be launched with your session login.

**Comment by jcarpent** [comment]
Maybe you will need to be sudo.

**Comment by andreadelprete** [comment]
I had to install omninames by doing
`sudo apt-get install omniorb-nameserver`
The problem seems to be that, for some obscure reason, the installation of pinocchio, gepetto-viewer and gepetto-viewer-corba via robotpkg binaries did not install all the dependencies of these packages, so now I need to install these dependencies by hand.

**Comment by florent-lamiraux** [comment]
You should report this to "robotpkg@laas.fr" so that Anthony fixes the issue.

**Comment by jmirabel** [comment]
Is this fixed ? If yes, could you close please ?

**Comment by MaximilienNaveau** [comment]
I have additionnal information on this.
I ran into this problem today and I understood that the problem appear when gepetto-viewer does not find the `omniORB.cfg` file.
This file is supposed to be in `/etc/omniORB.cfg`
In my case gepetto-viewer-server was looking at `/opt/openrobots/etc/omniORB.cfg`
You can check this by using `gepetto-viewer-server -ORBtraceLevel 10`
To solve the problem you can either create a symbolic link either force omniNames to look into the right forlder using the envirronement variables or the argument of omniNames.
I tried the first solutino and it worked for me.

**Comment by jmirabel** [comment]
I think @jcarpent mentioned this issue already, isn't it ?

> You just need to run for the first time omniNames with the command omniNames -start. It will create a config file in /etc/.
Afterwards, you won't need to redo the operation and omniNames will be launched with your session login.

**Comment by nmansard** [comment]
Everybody seems now happy. I close the issue.
