### ISSUE TITLE
addSceneToWindows reset the camera focus

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/gepetto-viewer-corba#55]
When re-adding the scene to the windows (typically) when the GVC client restarts), the camera view is reset to the home position. This behavior comes from Gepetto-Viewer, windows-manager.cpp:294, calling viewer_ptr->home() while home cannot be changed through the corba API.

Reseting to home automatically is not a nice behavior. I would suggest that this is removed from gepetto-viewer. Alternatively, we should add something in GVC API to prevent this behavior, or to enable the modification of the viewer home position.

This issue is related to #54 and #34

**Comment by jmirabel** [comment]
I do agree. See https://github.com/humanoid-path-planner/gepetto-viewer/pull/50

**Comment by nmansard** [comment]
Solved by humanoid-path-planner/gepetto-viewer#50.
