### ISSUE TITLE
Showing romeo in gepetto-gui

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/gepetto-viewer-corba#68]
Hi,

Loading Romeo as in the Pinocchio's tutorial in gepetto-gui on my 16.04 successfully shows the body tree, but doesn't show anything on the 3D view.

In the same setup, it works on gepetto-viewer-server, and ur5 is correctly displayed in both gepetto-gui and gepetto-viewer-server.

Which differences between gepetto-gui & gepetto-viewer-server could lead to this behavior ?

**Comment by jmirabel** [comment]
> Loading Romeo as in the Pinocchio's tutorial in gepetto-gui on my 16.04 successfully shows the body tree, but doesn't show anything on the 3D view.

A dirty fix is to run command:
```bash
find ${root_of_meshes_directory} -iname "*.dae" -type f -exec osgconv {} {}.osg \;
```

> Which differences between gepetto-gui & gepetto-viewer-server could lead to this behavior ?

Somehow, a conflict between Qt and OSG which I could not understand. On some computers, the DAE parser of OSG returns an empty object when inside gepetto-gui and a normal object when inside gepetto-viewer-server. There might be some hardware configuration involved.

**Comment by jmirabel** [comment]
See http://forum.openscenegraph.org/viewtopic.php?t=15657

**Comment by jcarpent** [comment]
@nim65s Does it work properly with the help of @jmirabel ?

**Comment by nim65s** [comment]
@jcarpent we have a workaround, but we are still looking for a clean solution

**Comment by jmirabel** [comment]
I found the bug !

The fault is from Collada Dom library. On my computer, Qt is settings the numeric locale to French (because it is the default on my computer). The Collada Dom uses sscanf to parse string as double. In French, the decimal separator is a comma, not a point so string("0.5423") gives double(0)...

See this bug report: https://sourceforge.net/p/collada-dom/bugs/137/

I will submit a fix.

**Comment by jmirabel** [comment]
Related to https://github.com/humanoid-path-planner/gepetto-viewer/pull/64 and
